### ISSUE TITLE
Placeholder text in "About Me" on Profile Page

### ISSUE THREAD

**Issue by ktracy2** [COSC481W-2023Fall/nestdoor-app#78]
**User Story**
As a logged in user, I want to update the "About Me" text on my profile.  If I have not updated this text yet, there is default placeholder text in the text box.  Once I update the text, it turns dark and lets the user know that their "About Me" has been updated.  

- **Persona:** A user with an account who is logged in
- **Feature:** Show placeholder text until the user enters their own "About Me" information
- **Business Value:** Users can see that the initial "About Me" text is default and when they personalize it and press "Change About Me" button, the text turns dark and looks more permanent. 

**Reference to the Beta Testing Report:**
Katie's Beta Testing Report: https://docs.google.com/document/d/1Av7MIn4CZ7LVAvPEfcCpJpL5SYE5vKzLIxGzd3IZsC8/edit?usp=drive_link
Item 4: 

> Tester said that the default text in the “About Me” text box should be light gray as a placeholder until the user has a 
> chance to add their own “About Me” content. 

**Tasks**

- [x] Style the initial text as a placeholder (Example: https://www.w3schools.com/tags/att_input_placeholder.asp)
- [x] The updated text will appear darker when the user presses the "Change About Me" button

**Acceptance Criteria**

1. When a new user has not updated their "About Me" content on their profile page, the text should appear grey and say "Tell us about yourself..."
2. When the user updates their "About Me" content by changing the text in the box and pressing "Change About Me" button, the text will appear black.

**Comment by hosulliv** [comment]
Successfully reviewed & merged
